# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx690tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.cache/wt [current_project]
set_property parent.project_path /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.4 [current_project]
add_files -quiet /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/sources_1/imports/new/Memory.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/sources_1/imports/new/pe_mux.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/sources_1/new/pe_encoder.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/sources_1/imports/new/pe_channel_used.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/sources_1/new/jet_cand.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/sources_1/imports/new/FoundJets.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/sources_1/new/Zbin.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/sources_1/imports/new/prio_mux8.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/sources_1/new/Layer1.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/sources_1/imports/new/LEDPLAY.v
}
read_xdc /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/constrs_1/imports/new/LEDPLAY_try1.xdc
set_property used_in_implementation false [get_files /home/gerstein/Xlinix/Vivado/2014.3.1/Layer1_cluster_cascaded/Layer1_cluster_cascaded.srcs/constrs_1/imports/new/LEDPLAY_try1.xdc]

catch { write_hwdef -file LEDPLAY.hwdef }
synth_design -top LEDPLAY -part xc7vx690tffg1761-2
write_checkpoint LEDPLAY.dcp
catch { report_utilization -file LEDPLAY_utilization_synth.rpt -pb LEDPLAY_utilization_synth.pb }
