# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx690tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.cache/wt [current_project]
set_property parent.project_path /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.4 [current_project]
add_files -quiet /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/imports/new/Memory.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/new/BetterFifo.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/new/unpack.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/new/tmux_gen.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/new/module_in.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/new/merge_pe.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/new/merge_mux.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/new/LtoG.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/new/link_mem.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/new/DTC_SM.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/new/DTC_top.v
  /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/sources_1/imports/new/LEDPLAY.v
}
read_xdc /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/constrs_1/imports/new/LEDPLAY_try1.xdc
set_property used_in_implementation false [get_files /home/gerstein/Xlinix/Vivado/2014.3.1/vc709_DTC/vc709_DTC.srcs/constrs_1/imports/new/LEDPLAY_try1.xdc]

catch { write_hwdef -file LEDPLAY.hwdef }
synth_design -top LEDPLAY -part xc7vx690tffg1761-2
write_checkpoint LEDPLAY.dcp
catch { report_utilization -file LEDPLAY_utilization_synth.rpt -pb LEDPLAY_utilization_synth.pb }
